In [21]:
#import pandas as pd
import numpy as np

p = np.array([0,1,4,5,34])

def resum(matriu):
    #df = pd.DataFrame(matriu)
    print("Resum estadístic de la matriu:")
    print("· media = ", np.mean(matriu))
    print("· mediana = ", np.median(matriu))        
    print("· mínimo = ", np.amin(matriu))
    print("· máximo = ", np.amax(matriu))
    print("· varianza = ", np.var(matriu))
    print(f"· desviación standard = {np.std(matriu):.2f}")
          
if p.ndim != 1:
    print("Hi ha una errada, la matriu no és d'una dimensió")
else:
    resum(p)


Resum estadístic de la matriu:
· media =  8.8
· mediana =  4.0
· mínimo =  0
· máximo =  34
· varianza =  162.16
· desviación standard = 12.73


In [3]:
from numpy import random

def matriuquadrada(n):
    x=random.randint(100, size=(n,n))
    print(x)
    
tamany = int(input("De quants números vols la matriu quadrada:  "))
matriuquadrada(tamany)

De quants números vols la matriu quadrada:  4
[[99  4 25 23]
 [74 84 92 33]
 [84 60  7 95]
 [23 32 94 62]]


In [6]:
import numpy as np

matriu = np.array([[0,1,4,5,34],[3,1,4,5,30]])

def sumatori(matriu2d):
    for i in range(np.shape(matriu)[0]):
        fila = sum(matriu[i])
        print("La suma de la fila", i, "és", fila)
    for i in range(np.shape(matriu)[1]):
        col = 0        
        for j in range(np.shape(matriu)[0]):
            col = col + matriu[j][i]
        print("La suma de la columna", i, "és", col)    

sumatori(matriu)

La suma de la fila 0 és 44
La suma de la fila 1 és 43
La suma de la columna 0 és 3
La suma de la columna 1 és 2
La suma de la columna 2 és 8
La suma de la columna 3 és 10
La suma de la columna 4 és 64


In [22]:
from numpy import random
import pandas as pd
import numpy as np

def calcorre(files):
    x=pd.DataFrame(random.randint(100, size=(tamany,2)))
    print(x)
    for j in range(x.ndim):
        addcol = []
        for i in range(len(x.index)):
            addcol.append(x[j][i] - x[j].mean())
        x[j+2] = addcol
    suman = 0
    sumad1 = 0
    sumad2  = 0
    for i in range(len(x.index)):
        suman = suman + (x[2][i]*x[3][i])
        sumad1 = sumad1 + (x[2][i])**2
        sumad2 = sumad2 + (x[3][i])**2
    corr = suman /(sumad1 * sumad2)** 0.5

    print(f"La correlació de les dues series de dades generats a l'atzar és: {corr:.5f}")

tamany = int(input("De quants números vols calcular la correlació:  "))
calcorre(tamany)

De quants números vols calcular la correlació:  4
    0   1
0  70  70
1  16  24
2  70  92
3   6  71
La correlació de les dues series de dades generats a l'atzar és: 0.58984
